from datetime import datetime, timedelta, timezone

CLEAN_DB=True
DROP_TABLE=True
DB_HOST="127.0.0.1"
DB_PORT="5432"
DB_NAME="mdf"
DB_USER="postgres"
DB_PASSWORD="postgres"
TYPE = None
FILE_PATH = None
CHUNK_SIZE = 1000
TABLE_PREFIX = "traj_"

REDDIT_CLIENT_ID=None
REDDIT_USERNAME=None
REDDIT_SECRET=None
SUBREDDIT=None
FROM_DATE=None
TO_DATE=None
SUBMISSIONS_BATCH_SIZE=5
NUM_ITERATIONS=-1
