DB_HOST="127.0.0.1"
DB_PORT="3306"
DB_NAME="reddit"
DB_USER="root"
DB_PASSWORD=None

REDDIT_CLIENT_ID=None
REDDIT_USERNAME=None
REDDIT_SECRET=None
SUBREDDIT=None
FROM_DATE=None
TO_DATE=None
SUBMISSIONS_BATCH_SIZE=10
NUM_ITERATIONS=-1
COMMENTS_PERSIST_BATCH_SIZE=1000
